CREATE TABLE SYS_USER (
	ID VARCHAR2(32) NOT NULL,
	USER_NAME VARCHAR2(32) NOT NULL,
	PASSWORD VARCHAR2(32) NOT NULL,
	USER_NUMBER VARCHAR2(32) NOT NULL,
	DISPLAY_NAME VARCHAR2(100) NOT NULL,
	EMAIL VARCHAR2(100),
	MOBILE_PHONE_NUMBER VARCHAR2(20),
	ADDRESS VARCHAR2(1000),
	DEPARTMENT_ID VARCHAR2(32),
	STATUS NUMBER(1) DEFAULT 0,
	DESCRIPTION VARCHAR2(500),
	CREATE_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL,
	CREATE_BY_USER_NAME VARCHAR2(32),
	CREATE_BY_USER_ID VARCHAR2(32),
	CONSTRAINT PK_SYS_USER PRIMARY KEY(ID),
	CONSTRAINT UNIQUE_SYS_USER_USERNAME UNIQUE(USER_NAME)
);
CREATE INDEX IDX_SYS_USER_STATUS ON SYS_USER(STATUS);
CREATE INDEX IDX_SYS_USER_DISPLAY_NAME ON SYS_USER(DISPLAY_NAME);
-- COMMENT ON TABLE SYS_USER IS 'ÓÃ»§ÐÅÏ¢±í';
-- COMMENT ON COLUMN SYS_USER.ID IS '±êÊ¶';
-- COMMENT ON COLUMN SYS_USER.NAME IS 'ÓÃ»§µÇÂ¼Ãû';
-- COMMENT ON COLUMN SYS_USER.PASSWORD IS 'ÓÃ»§µÇÂ¼ÃÜÂë';
-- COMMENT ON COLUMN SYS_USER.USER_NUMBER IS 'ÓÃ»§±àºÅ';
-- COMMENT ON COLUMN SYS_USER.DISPLAY_NAME IS 'ÓÃ»§ÏÔÊ¾Ãû³Æ';
-- COMMENT ON COLUMN SYS_USER.EMAIL IS 'ÓÃ»§ÓÊ¼þµØÖ·';
-- COMMENT ON COLUMN SYS_USER.MOBILE_PHONE_NUMBER IS 'ÒÆ¶¯ÊÖ»úºÅ';
-- COMMENT ON COLUMN SYS_USER.ADDRESS IS 'µØÖ·';
-- COMMENT ON COLUMN SYS_USER.DEPARTMENT_ID IS 'ËùÓÐ²¿ÃÅID';
-- COMMENT ON COLUMN SYS_USER.STATUS IS 'ÓÃ»§×´Ì¬¡£0£ºÕý³££»1£º½ûÓÃ£»2£ºËø¶¨';
-- COMMENT ON COLUMN SYS_USER.DESCRIPTION IS '±¸×¢';
-- COMMENT ON COLUMN SYS_USER.CREATE_DATE IS 'ÓÃ»§´´½¨Ê±¼ä';
-- COMMENT ON COLUMN SYS_USER.CREATE_BY_USER_ID IS 'ÓÃ»§µÄ´´½¨ÕßID';
-- COMMENT ON COLUMN SYS_USER.CREATE_BY_USER_NAME IS 'ÓÃ»§´´½¨ÕßÃû³Æ';
